# Generated by Django 5.2.7 on 2026-03-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.CharField(db_index=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=32)),
                ('span_id', models.CharField(db_index=True, max_length=16)),
                ('parent_span_id', models.CharField(blank=True, max_length=16, null=True)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'traces',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trace_id', 'created_at'], name='traces_trace_i_db67fa_idx')],
            },
        ),
    ]
