# Generated by Django 5.2.7 on 2026-04-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceflowApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='client_ip',
            field=models.CharField(blank=True, db_index=True, max_length=45, null=True),
        ),
    ]
