# Generated by Django 5.2.7 on 2026-05-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceflowApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('hash_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trace_hashes',
            },
        ),
    ]
