# Generated by Django 5.2.7 on 2026-04-11 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traceflowApp', '0002_trace_client_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trace',
            name='client_ip',
        ),
    ]
